# Generated by Django 5.0.7 on 2024-08-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.URLField(blank=True, help_text='URL of the video for the product', null=True),
        ),
    ]
